package com.medsecure.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

import com.medsecure.repository.PatientRepository;
import com.medsecure.repository.DoctorRepository;
import com.medsecure.repository.AppointmentRepository;
import com.medsecure.repository.BillRepository;

import jakarta.servlet.http.HttpServletResponse;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
@Controller
public class ReportsController {

    @Autowired
    private PatientRepository patientRepository;

    @Autowired
    private DoctorRepository doctorRepository;

    @Autowired
    private AppointmentRepository appointmentRepository;

    @Autowired
    private BillRepository billRepository;

    @GetMapping("/reports")
    public String reports(Model model) {

        model.addAttribute("patientCount",
                patientRepository.count());

        model.addAttribute("doctorCount",
                doctorRepository.count());

        model.addAttribute("appointmentCount",
                appointmentRepository.count());

        model.addAttribute("billCount",
                billRepository.count());

        double totalRevenue =
                billRepository.findAll()
                        .stream()
                        .mapToDouble(b -> b.getAmount() == null ? 0 : b.getAmount())
                        .sum();

        model.addAttribute("totalRevenue", totalRevenue);

        return "reports";
    }
    @GetMapping("/reports/pdf")
    public void downloadReport(
            HttpServletResponse response) throws Exception {

        response.setContentType("application/pdf");

        response.setHeader(
                "Content-Disposition",
                "attachment; filename=HospitalReport.pdf");

        PdfWriter writer =
                new PdfWriter(response.getOutputStream());

        PdfDocument pdfDocument =
                new PdfDocument(writer);

        Document document =
                new Document(pdfDocument);

        document.add(
                new Paragraph("MEDISECURE HOSPITAL MANAGEMENT SYSTEM"));

        document.add(
                new Paragraph("-------------------------------------------"));

        document.add(
                new Paragraph(
                        "Total Patients : "
                                + patientRepository.count()));

        document.add(
                new Paragraph(
                        "Total Doctors : "
                                + doctorRepository.count()));

        document.add(
                new Paragraph(
                        "Total Appointments : "
                                + appointmentRepository.count()));

        document.add(
                new Paragraph(
                        "Total Bills : "
                                + billRepository.count()));

        double revenue =
                billRepository.findAll()
                        .stream()
                        .mapToDouble(
                                b -> b.getAmount() == null
                                        ? 0
                                        : b.getAmount())
                        .sum();

        document.add(
                new Paragraph(
                        "Total Revenue : ₹ "
                                + revenue));

        document.add(
                new Paragraph(""));

        document.add(
                new Paragraph(
                        "Generated by MediSecure HMS"));

        document.close();
    }
    
}